### ISSUE TITLE
add link to MDFR safety inspection checklist

### ISSUE THREAD

**Issue by mathias-gibson** [codeforamerica/mdc-step-wizard#21] opened 2015-06-26 22:30 UTC
![pasted_image_6_26_15__3_26_pm](https://cloud.githubusercontent.com/assets/8147336/8388554/4883a942-1c18-11e5-9e36-c9310ab6d934.png)

**Comment by phiden** [comment] 2015-07-13 22:10
This is a dupe of a bunch of other issues.

**Closed as completed by phiden** 2015-07-13 22:10 UTC
Labels: duplicate, enhancement, content
